version: '3'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hugo/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hugo/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
